name: Generate JSON file
on:
  workflow_dispatch:

jobs:
  Generate-JSON-File:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and run application
        run: |
          ls -la
          cd ${{ github.workspace }}/scripts
          echo "Running typescript application..."
          npm install
          npm install @types/node --save-dev
          npm install -g typescript ts-node
          npm run start

      - name: Data.json as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: data.json
          path: ${{ github.workspace }}/scripts/data/*.json

      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
           commit_message: "updated data.json file with new data - $(date)"
           file_pattern: "scripts/data/*.json"
